# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftCheckApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftCheck'

  # Pods for SwiftCheckApp

  target 'SwiftCheckAppTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'SwiftCheck'
  end

  target 'SwiftCheckAppUITests' do
    # Pods for testing
    pod 'SwiftCheck'
  end

end
